### ISSUE TITLE
Add screenshots of what this IDE looks like and its best features

### ISSUE THREAD

**Issue by DinisCruz** [mark-hahn/node-ide#1]
It will be easier to give this a go (and to get the best out of it) it there was an easy way to see what it does

You can start by adding that info as an GitHub issue (since it support copy and paste of images from clipboard) See an example of what looks like here: https://github.com/o2platform/FluentSharp/issues/32

Then you can move that info into wiki pages (check out https://github.com/TeamMentor/TM_4_0_Design/wiki/Editing-this-wiki which shows how to use GH wiki as a repo)

**Comment by mark-hahn** [comment]
Thanks.  I'll do that.  

Meanwhile I have to actually get it finished so I have a screen to take a shot of (grin).  I put some really simple instructions up today in the readme because someone wanted to try it.  But I suggest putting off trying it.  It isn't even pre-alpha yet.  It will be at least a few weeks before it can be shown.

**Comment by DinisCruz** [comment]
ok, btw, i find that it really helps with my workflow to use GitHub issues to track what I'm doing and what needs to be done.

Not only it gives me a good list of 'small nuggets of work' to quickly work on next, it helps to keep track of ideas and it allow others to easily help (see for example some of the issues I added to https://github.com/o2platform/fluentnode/issues )

I'm also finding it a great to way ask questions directly to the key developers (like this thread for example :) )

**Comment by mark-hahn** [comment]
I agree.  However I'm still at a point where I have so much to do I
couldn't possibly turn it into a to-do list.

> I'm also finding it a great to way ask questions directly to the key
> developers

When this is released the best place to discuss it would be on the Atom
blog at https://discuss.atom.io.  More people will see the discussion there
than they would here.
